#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'sprint4-eurobot','console_scripts','cenital_node'
__requires__ = 'sprint4-eurobot'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('sprint4-eurobot', 'console_scripts', 'cenital_node')()
    )
