#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'sprint5-eurobot','console_scripts','string_navigator'
__requires__ = 'sprint5-eurobot'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('sprint5-eurobot', 'console_scripts', 'string_navigator')()
    )
